name: html+pdf generation with pandoc
run-name: ${{ github.actor }} is generating new slides 
on: [push]

env:
  PANDOC_VERSION: 2.10.1
  EMOJIONE_VERSION: 5.0.3

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make texlive
          version: 1.0    
      - run: |
         wget https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb -O pandoc.deb
         sudo dpkg -i pandoc.deb     
      - run: |
         wget https://github.com/joypixels/emoji-assets/archive/v${EMOJIONE_VERSION}.tar.gz -O emojione-assets.tgz
         tar xf emojione-assets.tgz
         mv emoji-assets-${EMOJIONE_VERSION} emojione-assets
         wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji.sty
         wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji-flags.sty
         sed -i 's/^\(\\usepackage{amsmath}\)/%\1/' xelatexemoji.sty
         sed -i 's/^\(\\providecommand{\\xelatexemojipath}\)/%\1/' xelatexemoji.sty      
      
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Run the Makefile
        run: |
          ls ${{ github.workspace }}
          make all
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the build repository
        run: |
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/build
          
      - run: make all
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
