name: html generation with pandoc
run-name: ${{ github.actor }} is generating new slides 
on: [push]

env:
  PANDOC_VERSION: 3.1.8
# EMOJIONE_VERSION: 8.0.0

jobs:
  md2html:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Job triggered by a ${{ github.event_name }}, running on ${{ runner.os }}"
      - run: |
         wget https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb -O pandoc.deb
         sudo dpkg -i pandoc.deb     
#      - run: |
#         wget https://github.com/joypixels/emoji-assets/archive/v${EMOJIONE_VERSION}.tar.gz -O emojione-assets.tgz
#         tar xf emojione-assets.tgz
#         mv emoji-assets-${EMOJIONE_VERSION} emojione-assets
#         wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji.sty
#         wget https://raw.githubusercontent.com/mreq/xelatex-emoji/master/xelatexemoji-flags.sty
#         sed -i 's/^\(\\usepackage{amsmath}\)/%\1/' xelatexemoji.sty
#         sed -i 's/^\(\\providecommand{\\xelatexemojipath}\)/%\1/' xelatexemoji.sty            

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The branch ${{ github.ref }} from ${{ github.repository }} has been cloned to the runner."

      - name: Run the Makefile
        run:  make slides # XeTeX : I can't find the format file `xelatex.fmt'!
                          # 2do : https://github.com/pandoc/pandoc-action-example
        
      - name: Add index
        run: |
          echo ${{ github.workspace }}
          cp /home/runner/work/slides-devweb/template/index.html /home/runner/work/slides-devweb/build
          cp /home/runner/work/slides-devweb/template/style.css /home/runner/work/slides-devweb/build
          echo "🖥️ build dir :"
          ls ${{ github.workspace }}/build  

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
      - run: echo "🍏 This job's status is ${{ job.status }}."
