name: Generation with pandoc
run-name: ${{ github.actor }} is generating new slides
on: [push, workflow_dispatch]

env:
  PANDOC_VERSION: 3.8

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ci-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - run: echo "🎉 Job triggered by a ${{ github.event_name }}, running on ${{ runner.os }}"

      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "💡 The branch ${{ github.ref }} from ${{ github.repository }} has been cloned to the runner."

      - name: Update apt
        run: >-
          sudo apt-get update -q
      - name: Upgrade apt
        run: >-
          sudo apt-get upgrade -qy
      - name: Install dependencies
        run: >-
          sudo apt-get install -qy
          fonts-inconsolata
          fonts-linuxlibertine
          fonts-noto
          fonts-texgyre
          latexmk
          lmodern
          make
          texlive-fonts-extra
          texlive-fonts-recommended
          texlive-lang-french
          texlive-latex-base
          texlive-latex-recommended
          texlive-luatex
          texlive-plain-generic
          texlive-science
          wget

      - run: |
         wget https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb -O pandoc.deb
         sudo dpkg -i pandoc.deb

      - name: Run the Makefile
        run:  make slides pdfs  # book is not ready

      - name: Add index
        run: |
          cp ./templates/index.html build/
          cp ./templates/style.css build/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          folder: build # The folder the action should deploy.
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
